trigger:
  branches:
    include:
    - master
  tags:
    include:
    - '*'
pr:
  autoCancel: false
  branches:
    include:
    - master

resources:
  repositories:
  - repository: PSModulePublisher
    type: github
    name: theohbrothers/PSModulePublisher
    endpoint: theohbrothers
    ref: refs/tags/v0.10.2
  - repository: PSRepositoryReleaseManager
    type: github
    name: theohbrothers/PSRepositoryReleaseManager
    endpoint: theohbrothers
    ref: refs/tags/v0.13.0

stages:
- stage: build_test
  displayName: Build, Test
  jobs:
  - job: windows_2022_powershell_core
    displayName: '[Windows Server 2022] PowerShell Core'
    pool:
      vmImage: windows-2022
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/windows/build-test.yml@PSModulePublisher
  - job: windows_2019_powershell_5_1
    displayName: '[Windows Server 2019] PowerShell 5.1'
    pool:
      vmImage: windows-2019
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/windows/powershell/build-test.yml@PSModulePublisher
  - job: ubuntu_2204_powershell_core
    displayName: '[Ubuntu 22.04] PowerShell Core'
    pool:
      vmImage: ubuntu-22.04
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/linux/build-test.yml@PSModulePublisher
  - job: ubuntu_2204_container_powershell_core
    displayName: '[Ubuntu 22.04] [Container] PowerShell'
    pool:
      vmImage: ubuntu-22.04
    strategy:
      matrix:
        7.4:
          containerImage: theohbrothers/docker-powershell:7.4-ubuntu-22.04-git
        7.3:
          containerImage: theohbrothers/docker-powershell:7.3-ubuntu-22.04-git
        7.2:
          containerImage: theohbrothers/docker-powershell:7.2-ubuntu-22.04-git
        7.1:
          containerImage: theohbrothers/docker-powershell:7.1.5-ubuntu-20.04-git
        7.0:
          containerImage: theohbrothers/docker-powershell:7.0.3-ubuntu-18.04-git
        6.2:
          containerImage: theohbrothers/docker-powershell:6.2.4-ubuntu-18.04-git
        6.1:
          containerImage: theohbrothers/docker-powershell:6.1.3-ubuntu-18.04-git
    container: $[ variables['containerImage'] ]
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/linux/build-test.yml@PSModulePublisher
  - job: macos_14_powershell_core
    displayName: '[macOS 14] PowerShell Core'
    pool:
      vmImage: macos-14
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/macos/build-test.yml@PSModulePublisher
- stage: build_publish
  displayName: Build, Publish
  dependsOn: build_test
  jobs:
  - job: windows_2019_powershell_5_1
    displayName: '[Windows Server 2019] PowerShell 5.1'
    pool:
      vmImage: windows-2019
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/windows/powershell/build-publish.yml@PSModulePublisher
- stage: release
  displayName: Release
  dependsOn: build_publish
  jobs:
  - job: ubuntu_2204_container_powershell_core
    displayName: '[Ubuntu 22.04] [Container] PowerShell Core'
    pool:
      vmImage: ubuntu-22.04
    container: theohbrothers/docker-powershell:7.2-ubuntu-22.04-git
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/generate.yml@PSRepositoryReleaseManager
    - template: templates/azure-pipelines/entrypoint/release.yml@PSRepositoryReleaseManager
